--- 
title: "Licensing R"
author: "Colin Fay"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Documenting the current state of licensing in the R world."
---

# Licensing R {-}

> Licensing for a package which might be distributed is an important but potentially complex subject.

<div class = "right"> 
[Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing)
</div>

## Disclaimer {-}

__This book is by no mean a legal book and should not be used as such. __

This book aims at helping you decipher the complexity of open source licenses, but if you have legal concerns and questions about open source licenses, __please refer to a professional lawyer__. 
Legal implications about licenses might differ from one company to another, or from one country to another? 

This book focuses on licensing R and R-related works. 
Hence a focus is made on GPL-based licenses (which are the licenses under which R is released). 

If you think there is a mistake somewhere, or if you want to contribute, please [open an issue on the GitHub repository](https://github.com/ThinkR-open/licensing-r/issues).

## What is this book about  {-}

This book aims at two things: 

- Documenting the current state of licensing in the R world, by exploring the CRAN and BioConductor databases.

- Helping developers make strategic choices about the license they apply to their R packages, by summarizing and explaining licenses and technical terms specific to open source licensing.

## Content  {-}

+ [Chapter 1 - Introduction](#intro) explores the current state of Open Source licenses by the number. In this chapter, we'll download and explore the data from CRAN and BioConductor databases.
+ [Chapter 2 - What is a license (and why you should care)](#whatis) gives a series of definition about common terms you'll find while browsing software licenses.  
+ [Chapter 3 - Licenses in the R World](#rworld), will present "officially supported" licenses and will try to classify them
+ [Chapter 4 - Common patterns for licensing R](#rlicense) will get into examples of licensing and practices
+ [Chapter 5 - A Practical Guide](#practical) gives you a quick overview of some methods to automate license adding
+ [Chapter 6 - Conclusion](#summary) will conclude this book


## Special Thanks  {-}

- This book is sponsored by an RConsortium ISC grant. 
Many thanks to them for supporting the project. 

- A special thank to [Miles McBain](https://milesmcbain.xyz/), who inspired this project.

## License   {-}

This book is released under the [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. 

You are free to:

+ Share this book
+ Adapt parts of the book 

Provided that:

+ You give attribution 
+ You don't use this material for commercial purposes
+ You share any modification under the same license

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
knitr::opts_chunk$set(
  fig.align = "center",
  rows.print=10, 
  cache = TRUE,
  cache.lazy = FALSE 
)

button_code <- function(){
  htmltools::HTML(
    '<div class "right" align = "right">
      <button class="favorite styled" type="button" 
      onclick = "$(\'.sourceCode\').toggle()">
      Show / Hide all code
      </button>
    </div>
    '
  )
}

hide_code <- function(){
  htmltools::tags$script(
    "$('.sourceCode').hide()"
  )
}

right_link <- function(text, link){
  htmltools::tagList(
    htmltools::singleton(
      htmltools::tags$style(
        ".right{ text-align: right;}"
      )
    ), 
    htmltools::tags$div(
      class = "right",
      htmltools::tags$a(
        href = link, 
        text
      )
    )
  )
}

with_tooltip <- function(text, tooltip){
  htmltools::tags$span(
    class = "tooltip", 
    text, 
    htmltools::tags$span(
      class="tooltiptext", 
      tooltip
    )
  )
}

disclaimer <- function(){
  htmltools::includeMarkdown("disclaimer")
}
```
